#ローカル用

version: "3.8"

services:

  hackathon_be:
    image: hackathon_test
    build:
      context: ../hackathon
    platform: linux/amd64
    ports:
      - "8000:8000"

    #docker-compose upで起動するときにgoが読み込む環境変数
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hackathon
      MYSQL_USER: irie
      MYSQL_PWD: iriepassword
      MYSQL_HOST: tcp(hackathon_develop_sql:3306)
    depends_on:
      - hackathon_develop_sql

  
  #hackathon_beコンテナが起動
  #Dockerfileを使ってGoをビルドし実行
  # hackathon_be:
  #   container_name: hackathon_be
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   platform: linux/amd64
  #   tty: true
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - mysql

  #Mysqlコンテナ
  #MySQLデータベースを起動



  hackathon_develop_sql:
    image: mysql:8.0
    container_name: hackathon_develop_sql
    platform: linux/x86_64
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hackathon
      MYSQL_USER: irie
      MYSQL_PASSWORD: iriepassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/1_users.sql:/docker-entrypoint-initdb.d/1_users.sql
      - ./database/2_posts.sql:/docker-entrypoint-initdb.d/2_posts.sql
      - ./database/3_likes.sql:/docker-entrypoint-initdb.d/3_likes.sql


volumes:
  mysql-data:
